Restaurant.create(name: "Le Rabelais", address: "LLN", category: "belgian")
Restaurant.create(name: "Le Cambridge", address: "LLN", category: "belgian")
Restaurant.create(name: "B' Comme", address: "LLN", category: "belgian")
Restaurant.create(name: "Les Saveurs du Siam", address: "LLN", category: "chinese")
Restaurant.create(name: "Il Fellini", address: "LLN", category: "italian")
